export const table_text_size = "text-xl"
export const rows_per_page = 8         // don't delete these "//"
export const json_users_filename = "./data/users.json"
export const json_employees_filename = "./data/employees.json"
export const json_settings_filename = "./Settings/settings.ts"
export const json_measurements_filename = "./data/measurements.json"
export const json_in_measure_filename = "./data/in_measure.json"
export const json_diagnoses_filename = "./data/diagnoses.json"